### ISSUE TITLE
自己搭建的mediawiki安装这个插件后无法保存修改。

### ISSUE THREAD

**Issue by litanwei** [Twinkle-Wikimedia/zhwp#1]
详细看了文档，是需要在服务器上安装sync.pl么？
其他都没有问题了。就是这部分没有安装。

**Comment by LNDDYL** [comment]
我雖是[Twinkle for Wikimedia projects](https://github.com/Twinkle-Wikimedia)計畫的發起者，但遺憾的是我並不是很懂代碼。我為了建立公版Twinkle而發起了此計畫，目前中文維基百科社群[正在討論此事](https://zh.wikipedia.org/wiki/Wikipedia:%E4%BA%92%E5%8A%A9%E5%AE%A2%E6%A0%88/%E6%8A%80%E6%9C%AF#%E9%87%8D%E6%96%B0%E5%BB%BA%E7%AB%8B%E4%B8%80%E5%80%8B%E5%8F%AF%E5%A4%9A%E4%BA%BA%E7%B6%AD%E8%AD%B7%E4%B8%94%E6%99%82%E5%B8%B8%E6%9B%B4%E6%96%B0%E7%9A%84%E5%85%AC%E7%89%88Twinkle)（本link將在中文維基站內本討論串存檔後失效）。

![default](https://user-images.githubusercontent.com/4318463/41445992-9fe4151e-707f-11e8-802f-39e26c26d58f.PNG)
圖中的這一段話是我留下的。

**Comment by LNDDYL** [comment]
我雖是[Twinkle for Wikimedia projects](https://github.com/Twinkle-Wikimedia)計畫的發起者，但遺憾的是我並不是很懂代碼。我為了建立公版Twinkle而發起了此計畫，目前中文維基百科社群[正在討論此事](https://zh.wikipedia.org/wiki/Wikipedia:%E4%BA%92%E5%8A%A9%E5%AE%A2%E6%A0%88/%E6%8A%80%E6%9C%AF#%E9%87%8D%E6%96%B0%E5%BB%BA%E7%AB%8B%E4%B8%80%E5%80%8B%E5%8F%AF%E5%A4%9A%E4%BA%BA%E7%B6%AD%E8%AD%B7%E4%B8%94%E6%99%82%E5%B8%B8%E6%9B%B4%E6%96%B0%E7%9A%84%E5%85%AC%E7%89%88Twinkle)（中文維基百科互助客栈中的討論串有存檔機制，本link將於討論串存檔後失效）。

![default](https://user-images.githubusercontent.com/4318463/41446052-fabb651e-707f-11e8-955b-e5a475f66aee.PNG)
圖中的這一段話是我留下的（在上方提供的link裡可以找到這段內容）。

**Comment by LNDDYL** [comment]
如果閣下有任何技術難題，請前往 https://zh.wikipedia.org/wiki/Wikipedia:互助客栈/技术 諮詢。

**Comment by Xi-Plus** [comment]
@litanwei 請仔細說明无法保存修改的狀況。

**Comment by litanwei** [comment]
我自己搭建了一个mediawiki，也按照说明安装了这个小工具，但是无法正常使用。
www.huatuo.org
你试一下。

谢谢楼上两位。

**Comment by Xi-Plus** [comment]
@litanwei 我沒有嘗試，但我想到可能的原因，請在[Special:标签](http://www.huatuo.org/Special:%E6%A0%87%E7%AD%BE)新增標籤：`Twinkle`

**Comment by LNDDYL** [comment]
`Fatal error: Call to undefined method MobileContext::getConfigVariable() in /var/www/html/skins/MinervaNeue/includes/Minerva.hooks.php on line 139`

你的網站壞了。
